"""Configuration for LLM processor in MMIRAGE."""

from dataclasses import dataclass, field

import logging
import os
from typing import ClassVar, Dict, Optional, Sequence, Type, Any, List
from pydantic import BaseModel, Field as PydanticField, create_model

from mmirage.config.batch_provider import BatchProviderConfig
from mmirage.core.process.variables import BaseVar, OutputVar

from mmirage.core.process.base import BaseProcessorConfig
from mmirage.core.process.base import ProcessorRegistry
from jinja2 import Environment, meta

logger = logging.getLogger(__name__)
env = Environment()


def _parse_tp_size_from_env() -> int:
    """Parse tensor parallelism size from SLURM_GPUS_ON_NODE environment variable.
    
    Defensively parses the environment variable, handling invalid values:
    - Returns 1 if the variable is None or empty
    - Strips whitespace before parsing
    - Returns 1 for non-integer values
    - Returns 1 for values <= 0
    
    Returns:
        Tensor parallelism size (>= 1), defaults to 1 on any parsing error.
    """
    env_value = os.environ.get("SLURM_GPUS_ON_NODE")
    if not env_value:
        return 1
    
    try:
        tp_size = int(env_value.strip())
        # Ensure tp_size is positive (must be >= 1)
        if tp_size <= 0:
            logger.warning(
                f"Invalid SLURM_GPUS_ON_NODE value '{env_value}' (must be > 0), defaulting tp_size to 1"
            )
            return 1
        return tp_size
    except ValueError:
        # ValueError: invalid integer format
        logger.warning(
            f"Invalid SLURM_GPUS_ON_NODE value '{env_value}', defaulting tp_size to 1"
        )
        return 1


@dataclass
class SGLangServerArgs:
    """Server arguments for SGLang engine.

    Attributes:
        model_path: Path to the model or HuggingFace model ID.
        tp_size: Tensor parallelism size.
        trust_remote_code: Whether to trust remote code from HuggingFace.
        disable_custom_all_reduce: Whether to disable custom all reduce.
        extra_engine_args: Any additional keyword arguments forwarded verbatim
            to ``sgl.Engine``. Use this to pass SGLang-specific options that
            are not listed above, e.g.::

                extra_engine_args:
                  max_running_requests: 512
                  chunked_prefill_size: 32768
                  mem_fraction_static: 0.88
    """

    model_path: str = "none"
    tp_size: int = field(default_factory=_parse_tp_size_from_env)
    trust_remote_code: bool = True
    disable_custom_all_reduce: bool = False
    extra_engine_args: Dict[str, Any] = field(default_factory=dict)


@dataclass
class SGLangLLMConfig(BaseProcessorConfig):
    """Configuration for LLM processor using SGLang.

    Supports both text-only and multimodal (vision-language) models.

    Attributes:
        type: Type identifier (must be "llm").
        server_args: SGLang server arguments including model path and TP size.
        default_sampling_params: Default sampling parameters for generation.
        chat_template: Chat template name for vision-language models (e.g., "qwen2-vl").
        batch_provider: Optional provider batch settings for async submission.
    """

    server_args: SGLangServerArgs = field(default_factory=SGLangServerArgs)
    default_sampling_params: Dict[str, Any] = field(default_factory=dict)
    chat_template: str = ""  # Empty means use tokenizer's default
    batch_provider: Optional[BatchProviderConfig] = None


@dataclass
class LLMOutputVar(OutputVar):
    """Output variable generated by LLM processor.

    Uses Jinja2 templating for prompts and supports both plain text
    and structured JSON outputs.

    Attributes:
        name: Name of the variable.
        type: Type identifier (must be "llm").
        prompt: Jinja2 template for the LLM prompt.
        output_schema: JSON output fields, either a list of field names
            (all typed as strings) or a mapping of field name to a type name
            ("str", "int", "float" or "bool") or to a nested mapping with keys
            `type` (required) and, for numeric types, optional `min`/`max`
            bounds enforced during constrained decoding. Empty for plain text.
        output_type: Output format - "JSON" or "plain".
    """

    SCHEMA_TYPE_MAP: ClassVar[dict[str, type]] = {
        "str": str,
        "string": str,
        "int": int,
        "integer": int,
        "float": float,
        "number": float,
        "bool": bool,
        "boolean": bool,
    }
    SCHEMA_FIELD_KEYS: ClassVar[set[str]] = {"type", "min", "max"}

    prompt: str = ""
    output_schema: list[str] | dict[str, Any] = field(default_factory=list)
    output_type: str = ""

    def _resolve_type(self, var: str, type_name: Any) -> type:
        """Map a schema type name ("int", "str", ...) to its Python type."""
        py_type = self.SCHEMA_TYPE_MAP.get(str(type_name).strip().lower())
        if py_type is None:
            raise ValueError(
                f"Unsupported type '{type_name}' for field '{var}' in output_schema "
                f"of '{self.name}'. Supported types: {sorted(self.SCHEMA_TYPE_MAP)}."
            )
        return py_type

    def _build_field(self, var: str, spec: Any) -> tuple[type, Any]:
        """Turn one output_schema entry into a `create_model` field spec."""
        if not isinstance(spec, dict):
            return (self._resolve_type(var, spec), ...)

        unknown = set(spec) - self.SCHEMA_FIELD_KEYS
        if unknown:
            raise ValueError(
                f"Unknown key(s) {sorted(unknown)} for field '{var}' in output_schema "
                f"of '{self.name}'. Allowed keys: {sorted(self.SCHEMA_FIELD_KEYS)}."
            )
        if "type" not in spec:
            raise ValueError(
                f"Field '{var}' in output_schema of '{self.name}' is "
                f"missing required key 'type'."
            )
        py_type = self._resolve_type(var, spec["type"])

        min_val, max_val = spec.get("min"), spec.get("max")
        if min_val is None and max_val is None:
            return (py_type, ...)
        if py_type not in (int, float):
            raise ValueError(
                f"'min'/'max' are only allowed for numeric types, but field '{var}' "
                f"in output_schema of '{self.name}' has type '{spec['type']}'."
            )
        if min_val is not None and max_val is not None and min_val > max_val:
            raise ValueError(
                f"min {min_val} cannot be greater than max {max_val} for field "
                f"'{var}' in output_schema of '{self.name}'."
            )
        return (py_type, PydanticField(ge=min_val, le=max_val))

    def has_schema_constraints(self) -> bool:
        """Whether any field declares a `min`/`max` bound."""
        if not isinstance(self.output_schema, dict):
            return False
        return any(
            isinstance(spec, dict)
            and (spec.get("min") is not None or spec.get("max") is not None)
            for spec in self.output_schema.values()
        )

    def get_output_schema(self) -> Optional[Type[BaseModel]]:
        """Generate a Pydantic model for JSON output validation.

        Returns:
            A Pydantic BaseModel class if output_type is "JSON" and
            output_schema is non-empty, otherwise None.

        Raises:
            ValueError: If output_schema maps a field to an unsupported type
                name or to an invalid constraint mapping.
        """
        if self.output_type == "JSON" and self.output_schema:
            fields: Dict[str, Any] = {}
            if isinstance(self.output_schema, dict):
                for var, spec in self.output_schema.items():
                    fields[var] = self._build_field(var, spec)
            else:
                fields = {var: (str, ...) for var in self.output_schema}
            return create_model("OutputSchema", **fields)
        return None

    def is_computable(self, vars: Sequence[BaseVar]) -> bool:
        """Check if all variables referenced in the prompt are available.

        Args:
            vars: Sequence of currently available variables.

        Returns:
            True if all template variables are declared, False otherwise.
        """
        parsed_content = env.parse(self.prompt)
        template_vars = meta.find_undeclared_variables(parsed_content)

        var_names = set(map(lambda v: v.name, vars))
        undeclared_vars = template_vars - var_names

        if len(undeclared_vars) > 0:
            logger.info(
                f"⚠️ Undeclared variables found for {self.name}: {undeclared_vars}"
            )
            return False

        return True


ProcessorRegistry.register_types("llm", SGLangLLMConfig, LLMOutputVar)
