"""Configuration for image generation processor in MMIRAGE."""

from dataclasses import dataclass, field

import logging
import os
from typing import Any, Dict, List, Literal, Optional, Sequence, TypeAlias
from jinja2 import Environment, meta

from mmirage.core.process.base import BaseProcessorConfig
from mmirage.core.process.base import ProcessorRegistry
from mmirage.core.process.variables import BaseVar, OutputVar

logger = logging.getLogger(__name__)
env = Environment()

ImageOutputMode: TypeAlias = Literal["path", "pil"]


@dataclass
class DiffusersPipelineArgs:
    """Runtime arguments used to initialize a Diffusers pipeline.

    Attributes:
        model_path: Hugging Face model id or local path.
        revision: Optional model revision.
        torch_dtype: Torch dtype as string. Common values: "float16", "bfloat16", "float32", "auto".
        device: Target device: "auto", "cuda", "cpu", or explicit device string.
        enable_attention_slicing: Enable attention slicing when available to reduce VRAM usage.
    """

    model_path: str = "stable-diffusion-v1-5/stable-diffusion-v1-5"
    revision: Optional[str] = None
    torch_dtype: str = "float16"
    device: str = "auto"
    enable_attention_slicing: bool = True


@dataclass
class DiffusersImageGenConfig(BaseProcessorConfig):
    """Configuration for image generation processor.

    Attributes:
        pipeline_args: Arguments used to initialize the Diffusers pipeline.
        default_sampling_params: Default generation kwargs passed to pipeline calls.
        parallel_inference: If True, process batch samples in parallel via a single batched pipeline call.
        parallel_chunk_size: Optional chunk size for batched calls. If None or <= 0,
            the full mapper batch size is used.
        output_dir: Directory where generated images are written when output_mode is "path".
        file_format: Image file format for saved outputs.
    """

    pipeline_args: DiffusersPipelineArgs = field(default_factory=DiffusersPipelineArgs)
    default_sampling_params: Dict[str, Any] = field(default_factory=dict)
    parallel_inference: bool = True
    parallel_chunk_size: Optional[int] = 4
    output_dir: str = ".mmirage/generated_images"
    file_format: str = "png"

    def __post_init__(self) -> None:
        """Validate optional parallelism settings."""
        if self.parallel_chunk_size is not None and self.parallel_chunk_size <= 0:
            self.parallel_chunk_size = None

    def get_output_dir(self) -> str:
        """Get normalized absolute output directory path."""
        return os.path.abspath(os.path.expanduser(self.output_dir))


@dataclass
class ImageGenOutputVar(OutputVar):
    """Output variable generated by image generation processor.

    Attributes:
        prompt: Jinja2 template used as positive prompt.
        negative_prompt: Optional Jinja2 template used as negative prompt.
        output_mode: Output representation: "path" (default) or "pil".
        filename_template: Optional Jinja2 template used for saved image filename stem.
            Supported internal variables: __sample_index (shard-global row index),
            __output_name, __shard_id, __source_hash (8-char SHA-256 of input values).
            All input variables (e.g. ``text``) are also available.
        width: Optional image width override.
        height: Optional image height override.
        num_inference_steps: Optional sampling steps override.
        guidance_scale: Optional guidance scale override.
        seed: Optional deterministic seed. If set, sample index is added for uniqueness.
    """

    prompt: str = ""
    negative_prompt: str = ""
    output_mode: ImageOutputMode = "path"
    filename_template: str = "generated_{{ __shard_id }}_{{ __sample_index }}_{{ __source_hash }}"
    width: Optional[int] = None
    height: Optional[int] = None
    num_inference_steps: Optional[int] = None
    guidance_scale: Optional[float] = None
    seed: Optional[int] = None

    def is_computable(self, vars: Sequence[BaseVar]) -> bool:
        """Check if all variables referenced in templates are available."""
        reserved = {"__sample_index", "__output_name", "__shard_id", "__source_hash"}
        var_names = {v.name for v in vars}

        # Prompt/negative_prompt are rendered from env.to_dict() only — reserved
        # vars are not injected there, so treat them as undeclared in those templates.
        prompt_templates: List[str] = [self.prompt]
        if self.negative_prompt:
            prompt_templates.append(self.negative_prompt)

        undeclared: set[str] = set()
        for template in prompt_templates:
            parsed_content = env.parse(template)
            template_vars = meta.find_undeclared_variables(parsed_content)
            undeclared |= template_vars - var_names

        # filename_template is rendered with reserved vars injected, so allow them.
        if self.filename_template:
            parsed_content = env.parse(self.filename_template)
            template_vars = meta.find_undeclared_variables(parsed_content)
            undeclared |= template_vars - var_names - reserved

        if undeclared:
            logger.warning(
                f"⚠️ Undeclared variables found for {self.name}: {undeclared}"
            )
            return False

        if self.output_mode not in {"path", "pil"}:
            logger.warning(
                f"⚠️ Invalid output_mode for {self.name}: {self.output_mode}. Expected one of ['path', 'pil']"
            )
            return False

        return True


ProcessorRegistry.register_types("image_gen", DiffusersImageGenConfig, ImageGenOutputVar)
