processors:
  - type: "custom"
    script_path: "./my_custom_logic.py"  
    function_name: "analyze_text" 
    max_workers: 4     
    timeout_ms: 2000     # by sample
    max_timeouts: 5      
    fallback_value: "TIMEOUT_FALLBACK"   #default value if it fails

loading_params:
  num_shards: 1
  batch_size: 100
  datasets:
    - type: "jsonl"
      path: "./data/input_data.jsonl"
      output_dir: "./output_data"

processing_params:
  inputs:
    - name: "my_text"      
      path: "original_text_column"
  
  outputs:
    - name: "custom_result"
      type: "custom"           
  
  output_schema:   
    source_text: "{{ my_text }}"
    analysis: "{{ custom_result }}"